[issue-#32] [NF]: Color Segmentation #32
lsd-maddrive/mnist_recognition pull request #37
Opened 2022-02-07 15:01 UTC by MarinaKupetskova

2022-02-07 15:57 UTC, serykhelena requested changes

2022-02-07 15:57 UTC, serykhelena commented on test/test_color_segmentation.py
> +PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
Возможно, от этой штуки поможет избавится, если внутрь папки object_detection положить пустой скрипт с именем `__init__.py`. Он помогает решать такие вот штуки с зависимостями. Попробуй, и елси сработает, все sys.path.append(PROJECT_ROOT) сноси (=

2022-02-07 15:57 UTC, serykhelena commented on test/test_color_segmentation.py
> +from test.data import *
когда сделаешь conftest.py этот импорт уже не будет нужен, pytest сам подтянет всё, что нужно

2022-02-07 15:57 UTC, serykhelena commented on test/test_color_segmentation.py
> +def test_1():
имена лушче более осмысленные давать, Например, `test_color_segmentation_sample_1`  и т.д. или вместо sample_1 ещё более точное описание давать. Не бойся длинных названий (=

2022-02-07 15:57 UTC, serykhelena commented on test/data.py
> +
Этот файл лучше оформить в виде conftest.py

2022-02-07 15:57 UTC, serykhelena commented on test/data.py
> +
погугли что это за зверь такой в pytest

2022-02-07 15:57 UTC, serykhelena commented on object_detection/segmentation/color_segmentation.py
> +
в эту же папку хочется файл utils, в котором будут лежать доп функции. Например, одна из них - функция, которая помогает подбирать пороговые значения. Можно сделать ГУИ-шку средствами opencv, как пример вот здесь https://codeloop.org/python-opencv-color-trackbar/ 

В результате эта функция должна создавать файл `color_thresholds.yaml` по пути, переданному в аргументах. Внутри файла должны пороговые значения или две маски: low и high

2022-02-07 15:57 UTC, serykhelena commented on object_detection/segmentation/color_segmentation.py
> +def color_segmentation (img:int,limit:int):
у тебя получается, что limit - это не просто int, а список пороговых значений. В этом случае аннотация типа не верная, тут должно быть `List[int]` (from typing import List) 
Также картинка, это не просто int, картинка = массив из uint_8 (обычно значения пикселя не бывает больше 255). Поэтому более правильно было бы написать `img: np.ndarray` 

А ты не хочешь в аргументах принимать просто 2 маски, одна для low-значений, вторая для high. Не списком, а прям сурово, напрямую? 

Также к этой функции не хватает docstring

2022-02-07 19:40 UTC, serykhelena requested changes

2022-02-07 19:40 UTC, serykhelena commented on .vscode/settings.json
> +{
Эту папку можно отправить в gitignore - это чисто внутренняя штука VSCode

2022-02-07 19:45 UTC, serykhelena commented
Давай ещё вместо папки Debug в notebooks, переименуем её в examples, и ноутбук с примером сегментации тоже переименуем в 01_color_segmentation_example.ipynb (что-то типа такого). 
Картинку давай положим в отдельную папку в tests/test_data - и в целом, можешь её использовать в тестах тоже, если нужно (=  Не забудь пути только правильные указать. 

Для ноутбуков есть прикольные магические команды. 
Например, 

```
%load_ext autoreload
%autoreload 2
``` 
Эти строки будут автоматически подтягивать изменения из модулей. То есть если ты что-то изменить в color_segmentation.py, тебе не нужно будет заново ячейки запускать, ноутбук сам загрузит изменения себе. 
Их можно прямо в первую ячейку в самый верх 1 раз добавить и всё. Это типа хак такой :sunglasses:

2022-02-12 14:02 UTC, serykhelena commented
В poetry dev нужно добавить модуль pytest

2022-02-12 14:02 UTC, serykhelena commented
В poetry dev нужно добавить модуль skimage

2022-02-14 11:47 UTC, MarinaKupetskova commented on object_detection/segmentation/color_segmentation.py
> +def color_segmentation (img:int,limit:int):
Внесла изменения, в аргументах теперь принимаю изображение и маски, но я пока все-таки не напрямую, а списком. (Так как я в ноутбуке и в тестах применяю разное кол-во масок). Но могу переделать

2022-02-14 18:41 UTC, serykhelena requested changes

2022-02-14 18:41 UTC, serykhelena commented on object_detection/segmentation/color_segmentation.py
> +    Description of the Function
здесь нужно написать, что эта функция делает (=

2022-02-14 18:41 UTC, serykhelena commented on object_detection/segmentation/color_segmentation.py
> +def color_segmentation (img:np.ndarray,masks:List[np.ndarray]):
не хватает возвращаемого значения через `->`

2022-02-14 18:41 UTC, serykhelena commented on object_detection/segmentation/utils.py
> +def trackChaned(x):
А эта фукнция зачем?

2022-02-14 18:41 UTC, serykhelena commented on object_detection/segmentation/utils.py
> +    Description of the Function
тоже опичания не хватает

2022-02-14 18:41 UTC, serykhelena commented on object_detection/segmentation/utils.py
> +def choose_threshold(img:np.ndarray):
указать возвращаемое значение через `->`

2022-02-14 18:41 UTC, serykhelena commented on object_detection/segmentation/utils.py
> +       #cv2.waitKey(0)
этот комментарий не нужен?

2022-02-14 18:41 UTC, serykhelena commented on test/test_color_segmentation.py
> +sys.path.append(PROJECT_ROOT)
нужно файл `__init__.py` положить внутрь папки object_detection (где исходники лежать). В корне репозитория этот файл не нужен (= Проверь ещё раз после этого, по идее, эти строки больше не нужны будут (=

2022-02-14 18:42 UTC, serykhelena commented
1) Проверь ещё раз штуку с `__init__.py` - убрать sys.path.append в тестах и в ноутбуке 
2) добавить тест с реальной картинкой - а то сейчас она лежит в папке с тестами, но никак не используется

2022-02-21 07:42 UTC, serykhelena requested changes

2022-02-21 07:42 UTC, serykhelena commented on Scripts/Examples.py
> +
Почитай про такую штуку 
`if __name__ == "__main__"`

В скриптах лучше добавлять такую конструкцию, чтобы твой код нельзя было использовать как библиотеку

2022-02-21 07:42 UTC, serykhelena commented on Scripts/Examples.py
> +sys.path.append(PROJECT_ROOT)
poetry всё ещё не работает?

2022-02-21 07:42 UTC, serykhelena commented on object_detection/segmentation/color_segmentation.py
> +    Description of the Function
Строку с Description oа the Function можно удалить (= Оставить только информацию по существу

2022-02-21 07:42 UTC, serykhelena commented on Scripts/Examples.py
> +sys.path.append(PROJECT_ROOT)
Кстати, а как ты запускаешь скрипт? Просто, если ты сразу не активируешь виртуальное окружение поетри, то нужно использовать команду: `poetry run python Scripts/Examples.py` ЛИБО 
1) `poetry shell`
2) `python Scripts/Examples.py`

2022-02-21 07:42 UTC, serykhelena commented on Scripts/Examples.py
> +    return mask
Здесь у тебя возвращается маска как картинка, а хочется ещё получить пороговые значения

2022-02-21 07:43 UTC, serykhelena commented
В папку Scripts не нужно файл `__init__.py`, так как это исполняемые скрипты, а не исходники библиотеки. Написала комментарий про поетри, попробуй запускать скрипты через ту команду, может быть поможет (=

2022-02-23 18:56 UTC, MarinaKupetskova commented
Попробовала запускать скрипт этой командой poetry _run python Scripts/Examples.py_ и вторым вариантом, но без добавления пути все равно ругается на то что ему не найти модуль =(

2022-02-24 08:36 UTC, serykhelena approved these changes

2022-02-24 08:38 UTC, merged