Issue #43 eda
lsd-maddrive/mnist_recognition pull request #44
Opened 2022-03-02 09:40 UTC by MarinaKupetskova

2022-03-03 10:03 UTC, MarinaKupetskova commented
Датасет в формате csv брада отсюда [Kaggle mnist ](https://www.kaggle.com/oddrationale/mnist-in-csv)

2022-03-08 14:34 UTC, serykhelena commented
Я внутри ноутбука добавила код для формирования датафрейма, без необходимости скачивать csv файл. В твой анализ нужно добавить по-отдельно анализ для каждой из выборок (обучающей, валидационной и тестовой). По сути это будет один и тот же код, но с разными цифрами и графиками. 

То есть, что нужно поправить: 
1. Изменить имя ноутбука - initial_analysis_MNIST (что-нибудь типа такого)
2. Добавить анализ по каждой из выборок внутри ноутбука
3. Добавить код по TODO (я оставить пару внутри ноутбука)

2022-03-08 14:35 UTC, serykhelena requested changes

2022-03-08 14:35 UTC, serykhelena commented on .gitignore
> +mnist_train.csv
Этот файл больше не нужен будет (=

2022-03-14 08:18 UTC, serykhelena approved these changes

2022-03-14 08:18 UTC, merged