Issue#48 fgsm attack notebook
lsd-maddrive/mnist_recognition pull request #58
Opened 2022-04-20 17:35 UTC by MarinaKupetskova

2022-04-21 10:31 UTC, serykhelena requested changes
1. Здесь избыточен второй Compose
```
transform = transforms.Compose(
    [Invertor(),transforms.Compose([transforms.ToTensor()])]
    )
```
Можно проще 

```
transform = transforms.Compose(
    [
        Invertor(),
        transforms.ToTensor()
    ]
)
```

2  В функции data_fgsm_attack строка 35

```
perturbed_data = np.reshape(perturbed_data.detach().numpy(),(28,28))
```

Должно быть 

```
perturbed_data = np.reshape(perturbed_data.cpu().detach().numpy(),(28,28))
```

Иначе на машине с видяхой - падает 

3 Вынести в отдельную переменную SAVE_DPATH 

```
SAVE_DPATH = os.path.join(PROJECT_ROOT,'results','mnist_fgsm_attacks')
os.makedirs(SAVE_DPATH, exist_ok=True)
```
Когда папки mnist_fgsm_attacks нет, то код падает при сохранении 

4. Добавить в ноутбук визуализацию картинок. Исходная картинка - та же картинка с атакой (с указанием значения эпсилон). Можно через interact

2022-04-24 07:57 UTC, serykhelena requested changes
Было бы здорово добавить предсказание для исходной картинки (без атак) и предсказание с атаками, чтобы сразу увидеть влияние. А то сейчас не очень понятно Predicted Label к чему относится, т.к. 2 картинки идут потом  
![image](https://user-images.githubusercontent.com/26322075/164966195-c8f1cd9c-a64c-4f00-904a-dfa7afe85a3f.png)

2022-04-24 10:07 UTC, MarinaKupetskova commented
Вывод метрик для оригинальных изображений оставить или лучше убрать?

2022-04-24 13:30 UTC, serykhelena approved these changes

2022-04-24 13:30 UTC, merged

2022-04-24 13:30 UTC, serykhelena commented
> Вывод метрик для оригинальных изображений оставить или лучше убрать?

Пусть пока будут (=